version: "3"

services:
  liip-ghost:
    image: liip/ghost-4.9.0
    container_name: liip-ghost
    restart: unless-stopped
    volumes:
      - "../core:/var/lib/ghost/core"
      - "../content:/var/lib/ghost/content"
    ports:
      - "3000:2368"
    environment:
      - NODE_ENV=development
      - url=http://localhost:3000
